server/app/main.py
from flask import Flask

from .views import bp as views_bp
from . import database
from . import filters
from .assets import asset_url, asset_url_debug
from .setup.configure import configure
from .setup.init_db import init_db

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('app.defaultconfig')
    app.config.from_pyfile('config.py', silent=True)

    app.register_blueprint(views_bp)
    app.teardown_appcontext(lambda e: database.close_connection())

    app.jinja_env.filters['quote_plus'] = filters.quote_plus_filter #pylint: disable=no-member
    app.jinja_env.filters['age'] = filters.age_filter  #pylint: disable=no-member
    if app.debug:
        app.jinja_env.globals['asset_url'] = asset_url_debug #pylint: disable=no-member
    else:
        app.jinja_env.globals['asset_url'] = asset_url #pylint: disable=no-member

    app.cli.command()(configure)
    app.cli.command('init-db')(init_db)
    return app

server/app/tablefilter/__init__.py
from .exceptions import QuerySyntaxError
from .query import Query

def match_row(query_str, row, *, column_names=None):
    return Query(query_str, column_names).match_row(row)

def match_word(query_str, word):
    return Query(query_str).match_word(word)

server/app/views.py
from marshmallow import ValidationError
from flask import Blueprint, request, abort, render_template, redirect, url_for

from .reports import REPORT_SCHEMA
from .search import search_db
from . import database

bp = Blueprint('views', __name__)

@bp.route('/api/1.0/save_report', methods=['POST'])
def save_report():
    conn = database.get_connection()
    try:
        report = REPORT_SCHEMA.load(request.json)
        print(report)
    except ValidationError:
        abort(400)
    else:
        report.save(conn)
        conn.commit()
    
    return '', 204


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/search')
def search():
    query_str = request.args['q']
    if not query_str:
        return redirect(url_for('views.index'))
    try:
        sort_key = int(request.args.get('s', 0))
        reverse = int(request.args.get('r', 0))
    except ValueError:
        abort(400)
    table = search_db(database.get_connection(), query_str, sort_key, reverse)
    return render_template('search.html', **locals())

server/app/templates/base.html
{% from 'macros/_navigation.html' import navigation_tab %}
<!DOCTYPE html>
<html>
<head>
	<link href="{{ asset_url('style.css') }}" rel="stylesheet">
	{% block title %}<title>{{ title }}{% endblock %}
</head>
<body>
	{% block header %}
	<div class="header">
		<div class="header-title">
			<a href="{{ url_for('views.index') }}">
				<span class="text">Simple Software Reports</span>
			</a>
		</div>
		
		<div class="navigation-tabs">
			{{ navigation_tab('views.index', 'Search') }}
			{# navigation_tab('clients.index', 'Clients') #}
		</div>
	</div>
	{% endblock %}
	
	<div class="content">
		{% block content %}{% endblock %}
	</div>
	
	<div class="footer">(c) 2019 sphipu</div>
</body>
</html>

server/app/templates/index.html
{% extends "base.html" %}

{%block title %}<title>Simple Software Reports</title>{% endblock %}

{% block content %}
<div class="flex-center fill-content">
	<div class="search-form-big">
		<div class="search-title">
			<span class="text">Simple Software Reports search</span>
		</div>
		<form method="GET" action="{{ url_for('views.search') }}" class="search-form">
			<input class="form-control" name="q" type="text" placeholder="Search" class="search-field">
			<button class="search-button button" type="submit">Search</button>
		</form>
	</div>
</div>
{% endblock %}

server/app/templates/macros/_navigation.html
{% macro navigation_tab(endpoint, text) %}
<div class="navigation-tab {{ 'active' if request.url_rule.endpoint == endpoint }}">
	<a href="{{ url_for(endpoint) }}">
		<span class="text">{{ text }}</span>
	</a>
</div>
{% endmacro %}

server/app/templates/search.html
{% extends 'base.html' %}

{% block title %}
	<title>Simple Software REports - {{ query_str }}</title>
{% endblock %}

{% macro sortable_header(text, key) %}
<th class="sortable">
	{% set reverse_item = sort_key == key and not reverse %}
	<a href="?q={{ query_str | quote_plus }}&s={{ key }}&r={{ '1' if reverse_item else 0 }}"
	   class="{{ 'sorted' if key == sort_key }}{{ '-reversed' if key == sort_key and not reverse_item }}">
		{{ text }}
	</a>
</th>
{% endmacro %}

{% block content %}
	<form method="GET" action="{{ url_for('views.search') }}" class="search-form">
		<div class="form-group-addon">
			<input class="form-control search-box" name="q" type="text" value="{{ query_str }}">
			<button type="submit" class="addon addon-right button">Search</button>
		</div>
	</form>
	<table class="table">
		<tr>
			{{ sortable_header('Computer Name', 0) }}
			{{ sortable_header('Software', 1) }}
			{{ sortable_header('Version', 2) }}
			{{ sortable_header('Current User', 3) }}
			{{ sortable_header('Software Publisher', 4) }}
			{{ sortable_header('Last Connection', 5) }}
		</tr>
		{% for row in table %}
		<tr>
			<td>{{ row.computer }}</td>
			<td>{{ row.software }}</td>
			<td>{{ row.version }}</td>
			<td>{{ row.user }}</td>
			<td>{{ row.publisher }}</td>
			<td>{{ row.last_connection | age }}</td>
		</tr>
		{% endfor %}
	</table>
	
{% endblock %}